Set family to "contrib" and check for jq in autoconf

diff --git a/plugins/go_echarger_efficiency b/plugins/go_echarger_efficiency
--- a/plugins/go_echarger_efficiency
+++ b/plugins/go_echarger_efficiency
@@ -31,7 +31,7 @@ GPLv2
 
 =head1 MAGIC MARKERS
 
- #%# family=auto
+ #%# family=contrib
  #%# capabilities=autoconf
 
 =cut
@@ -73,10 +73,12 @@ EOF
         exit 0
 		;;
 	autoconf)
-		if echo "" | nc -q1 "$host" "80" > /dev/null 2>&1 ; then
-			echo "yes"
-		else
+		if ! jq --version > /dev/null; then
+			echo "no ('jq' not found. Is it installed and in PATH?)"
+		elif ! echo "" | nc -q1 "$host" "80" > /dev/null 2>&1 ; then
 			echo "no (Connection to ${host}:80 failed.)"
+		else
+			echo "yes"
 		fi
 		exit 0
 		;;
